### ISSUE TITLE
Find the right syntaxe to user tip and color 

### ISSUE THREAD

**Issue by tigerfoot** [chdemko/pandoc-latex-tip#8]
Hi I'm having some trouble to fix my use case.
I would like to have (if possible) only one keyword for geting a latex-tip + a latex-color define.

Like a comment icon in lightskylblue and text in that div also in blue.

Creating two divs seems to work, but I would like to have only one

```
pandoc-latex-color:
  - classes: [comments]
    color: lightskyblue
pandoc-latex-tip:
  - classes: [tip, comments]
    icons: [{name: comments-alt, color: lightskyblue, version: 5.0, variant: regular}]
    size: 18
    position: left
```

The idea would be to have in markdown a sample

::: comments ::: 
block text in blue with nice icons
:::

Thanks for any ideas or pointer.

**Comment by chdemko** [comment]
Hi
I'm currently on holidays. I will have a look in a couple of days

**Comment by tigerfoot** [comment]
In the meantime, I've been able to mix the 3 (so great) filters I want to use in the following way

```yaml
pandoc-latex-color:
  - classes: [color, bug]
    color: olivedrab
  - classes: [color]
    color: black
# Extension pour ajouter un bloc de couleur vertical dans la marge droite ou gauche
pandoc-latex-admonition:
  - classes: [admonition, bomb]
    color: red
    linewidth: 2
    position: right
  - classes: [admonition]
# Extension pandoc-latex-tip qui met de jolis icones fontawesome
# dans le document
pandoc-latex-tip:
  - classes: [tip, bomb]
    icons: [{name: bomb, color: red, version: 5.x, variant: solid}]
    size: 22
    position: left
  - classes: [tip]
```

```markdown



:::: {.tip .bomb .admonition .bomb .color .bomb} ::::

----

1. Your bombing content list
1. No
1. Never
1. Don't

----

:::

```

Then still yes have a ::: bomb ::: working syntax would be a big plus.
